"""init

Revision ID: edf8aa00cd34
Revises: 8c76168e0b6d
Create Date: 2025-01-11 20:24:05.043092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf8aa00cd34'
down_revision: Union[str, None] = '8c76168e0b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('number_of_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'number_of_attempts')
    # ### end Alembic commands ###
